version: '3.8'
services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:80'
    depends_on:
      - db


  db:
    image: mongo:latest
    ports:
      - '27017:27017'
    
